### ISSUE TITLE
Needs more recent versions on the downloads page?

### ISSUE THREAD

**Issue by zsfre** [AlloyTools/alloytools.github.io#21]
I had to struggle a while with version 4.2 while it turns out there's a 5.1

**Comment by pkriens** [comment]
Which page?

**Comment by zsfre** [comment]
This one http://alloytools.org/download.html

And now I see I’m an idiot because it’s in the experimental release.

S

Written with thumbs. Please excuse autocorrections and errors

On 19 Oct 2019, at 10:25, Peter Kriens <notifications@github.com> wrote:

﻿

Which page?
