### ISSUE TITLE
Alloy6 image links broken

### ISSUE THREAD

**Issue by hwayne** [AlloyTools/alloytools.github.io#37]
![image](https://user-images.githubusercontent.com/2660212/141041644-0d45e6e0-e032-4ee6-b296-b05f45d3dae2.png)

The "alloy 6" above the `Mutable` header should be an image.

**Comment by grayswandyr** [comment]
Yep, I had made the fix but forgottent to make a PR :-)
This is done now in #38 .

**Comment by grayswandyr** [comment]
#38 merged.
