### ISSUE TITLE
Ensure liveliness of links on Alloy's public website

### ISSUE THREAD

**Issue by ma7madsayed** [AlloyTools/alloytools.github.io#44]
Hello!
 Multiple pages(citations, applications, etc.) have  issues with the links. The issues vary from the content  exists but the links need updating to contents no longer there, to domains no longer valid.
 I will be submitting a pull request with fixes so per the guidelines this is the issue/branch I will be referencing.
Thanks for all the hard work!

**Comment by grayswandyr** [comment]
Thanks!
